# Lesson 5 Practical Application
## C2C David Mottice

### #1 Create an array containing 4 string elements: first name, last name, birth state, and favorite color.

a. Use a numpy function to make all elements uppercase

In [2]:
import numpy as np
from datascience import * 

In [3]:
me = np.array(['David', 'Mottice', 'Florida', 'Green'])
me

array(['David', 'Mottice', 'Florida', 'Green'], dtype='<U7')

In [4]:
np.char.upper(me)

array(['DAVID', 'MOTTICE', 'FLORIDA', 'GREEN'], dtype='<U7')

b. Use a numpy function to count the number of times the letter "a" appears in each element of your array.

In [5]:
np.char.count(me, 'a')

array([1, 0, 1, 0])

### OPTIONAL: Use a numpy function to find the length of each element in the array. You may need Google to do this.

In [16]:
type(1.0)

float

## #2 Create an array containing every other odd number starting with 1 and ending with (including) 41.

a. Use numpy to find the sum and the product of the elements of this array

In [19]:
odd = np.arange(1,42,4)*1.0
odd

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

In [20]:
print(np.sum(odd))
print(np.prod(odd))

231.0
7579867420125.0


b. Use a numpy to take the natural log of each element.

In [40]:
print(np.log10(odd))

[0.         0.69897    0.95424251 1.11394335 1.23044892 1.32221929
 1.39794001 1.462398   1.51851394 1.56820172 1.61278386 1.65321251]


### #3 OPTIONAL: The numpy function np.diff finds the difference between adjacent elemens of an array. Find the SUM of adjacent elements of this array. 

In [38]:
first = odd[0:len(odd)-1]
second = odd[1:len(odd)]
print(first+second)

[ 6 14 22 30 38 46 54 62 70 78 86]
